### ISSUE TITLE
Segfault in zfs-mount-generator makes system unbootable

### ISSUE THREAD

**Issue by nirvdrum** [ubuntu/zsys#62]
I've spent a couple days debugging this, but I'm not well-versed in ZFS's internals, so apologies if I flub some details. I have a system with three pools: `bpool` (created by Ubuntu installer), `rpool` (created by Ubuntu installer), and `extra`, which is a pool from a previous installation.

For some reason, `zfs-mount-generator` doesn't like my `extra` pool. Tracking this down was a bit tricky because it's invoked automatically. And since I never imported my `extra` pool, I didn't expect it would be processed by anything. In any event, when invoked with the the `extra` pool available, `zfs-mount-generator` segfaults:

```
❯ sudo /usr/lib/systemd/system-generators/zfs-mount-generator
WARNING MountPoint property for "extra" has an unexpected source: "default" 
WARNING MountPoint property for "extra/home" has an unexpected source: "default" 
WARNING MountPoint property for "extra/home/nirvdrum" has an unexpected source: "default" 
WARNING MountPoint property for "extra/home/kjmenard" has an unexpected source: "default" 
WARNING MountPoint property for "extra/home/root" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/nfs" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/games" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/log" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/spool" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/tmp" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/cache" has an unexpected source: "default" 
WARNING MountPoint property for "extra/var/vmware" has an unexpected source: "default" 
WARNING CanMount property for "extra/swap" has an unexpected source: "" 
WARNING MountPoint property for "extra/ROOT" has an unexpected source: "default" 
WARNING MountPoint property for "extra/ROOT/ubuntu" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/dbae36df9b906461576510f5e597405cfd008044358202b2852d83f18902813f" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/6e4d34e6a987699828854060d17eaad39b51b825bc5420047867152abfabeab9" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/047acf4966c1ec540109c254d6c974b5b1bb6409356d98e0e1d4134ac99933fa" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/aee091c261fe80e2885760c680196da25d7188a2a810eb1040e1424df7a9f803" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/d1b9e33550fd78babf1c7a27817397da2c1c2fcad683e021dfc39922ed62777e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/b4d66da03719b6e6263cdca3a00dd90b56263c7e21828419648a2a6febd02416" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/a1195a91e292004acf1016c699f2b88b4f5ce291829b7d1f577f586cebc4774d" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/4a88c48d41a19cef8f04e3bbfc43ccd0b1f8d367532b50a14c555d947919d31d-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/4224f2470d0a254c9af8275529ffc5d00b56671cdf13b3ac87f2bfef652420c9-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/b8fe6b4a3b3be22698bc2f7d4370bf822d116f0639c8ab1b459bed6d222fd29e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/3ebf5f24734496b8715d2942a23985a9ebb4d4fc91f85f7ca688f852481e96e6-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/6d801053ae12203c55753efbe28df8d831ed3dacb8d2bebb8b87a51e43df86ac" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/34bfec2f54ae7a95fdb009adffdd957f05272b4518e3980716de20b919fed79d" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/257da3ec4572e53586faa307c31844200091fa4746f8fcfd88acc4d4d5f709f7" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/fd5e95d59cd8632889dcaf869c05e76c96a9fadfd9c813cd953701d1b4c9579e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/1573d1e7552d26a7683bbdab9c927ed7f3a72ef65614b866debdabb472a5b9e9-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/3fadad7fd99e6ea5c5259dae7a3812d083e574a49c6c1b4bc417dae73d828749" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/8db952a965cd38f14baba6b82815a8aa6baeab13695f818b6204e5179f3e3d19" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/ac0ba3f58669b585ae88b6abff308e66fd53f45c137dd8a06d02a317808ee843" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/57a81abfaaea018fb9d147f6b5e122f02c099b7b295ee1d20bfefa0ff4fd2e54-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/74a22ede013a259b0c203ba24aecbe0065874d6fb148e3e54107521615ab32ab" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/09c729767fd6cb7f6c46ee1deea90b1572cba6834c19d2fd71dd162b5db0040f" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/53333300c56f2540106469fa23f786d161c8a66828836e9f8309bfb2201524b9" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/46fd7eef8aac9c7211a38c877e4161c8f13dc518fa9661dd2527473bad1fe7b8" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/2a881d3f09c5f025e5517d74bbe35e2ae140ee08bc9f74e9b16f0ec907b5cd11" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/d0461b1859fab765d0dc13b5e35edbc3ee658d241a89109db53dcb9ac180f07e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/3ebf5f24734496b8715d2942a23985a9ebb4d4fc91f85f7ca688f852481e96e6" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/c66c88dc0cf6a2b8db05994a33ad4535837583fa56339aabaaf7ab932a9278c7" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/fd9f68f7567ee2cd0e0ae2bfbb3f99e0bb64b51fafc9445932b85507ff03149f-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/99b2d73a65335b11d6321ed748b46f9018c037b1cd33bf722664bbe3697fd8ff" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/d31e275215ee9667d3838aff85e211572c3f436099ae5d62b9cf16509cd67485" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/f3ad5cd0ec438d7ef6a92a5a26e620d1288ec166c8a63f2834f42fe1732a6b09" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/2278ec91a15de1786bf80d7353e5336d64d8d3dfd6b157fc1d4b82cfdeaead62" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/1fb57c326eac7ce58c6f15db29fc4a8ecf416f9c337dc719cd5fc8a0b6317c48" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/30304c7b1cc2157b4eb852c7c925568549a2d40b614fadd98c33674dfe825bcd" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/751d2a798c2a851ef0265faca68dddb73577acd195283aae729df57f806a0284" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/24575b535fa6139c90fbe91a2cf54a15e8da960dd6701e27896a9777b7337833" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/d9602ed7d67f679b1a825843025c4c5a938dc5931a4461f519b17231723b71fe" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/85d039b186a473100f208fcf3420c37b0cba4c2da82f86c3b46eab0fcc3916df" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/c5ecd0d4628bd178c3cf64b97d180c9a263f8b16c15fafbbf21daa57d2000156" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/1573d1e7552d26a7683bbdab9c927ed7f3a72ef65614b866debdabb472a5b9e9" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/b573116477f0e1077608e5e38d3dd75232538db9d71b0530827121eb9858640d" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/fd9f68f7567ee2cd0e0ae2bfbb3f99e0bb64b51fafc9445932b85507ff03149f" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/30304c7b1cc2157b4eb852c7c925568549a2d40b614fadd98c33674dfe825bcd-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/515bd8e9f381e6ff1db42c86ac836ded694f09c52b4a6db997ad9c44f0ae0705-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/b53223fe6a543698ffd8c2b70acdcd9ca40efba3326d4b8de38432ea1171e5c0" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/c7631d51116039ebfebf1f12d9042dab83ce99ec448e47dd1eafbd15386a69f6" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/e96698e37e6e99827aec21afbef983d4d841d0d889fd5ee1b1ea262ffb3a5321" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/c5ecd0d4628bd178c3cf64b97d180c9a263f8b16c15fafbbf21daa57d2000156-init" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/1af8a07f1f212227fd6dc0080fd150235056b91841022c2a5f68546102d7032e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/bdbbb33488a36cfd0a7536a53b48a564fdb503e03e02dba6211a78f6ea7f868c" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/9e96c2f530a86a9e8550341058d427dc58f6dbda46552034fcf2a6e91dd3870e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/0a463bfa3f2a50f2392aa4fdec5a0be1fa3097ceaa3bcdba2827a465abe92d8f" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/4a88c48d41a19cef8f04e3bbfc43ccd0b1f8d367532b50a14c555d947919d31d" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/546962dd7f5eac5a8e2cdf1d6afb139dca8202ff65df6f78a3be4ced356eb889" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/3af0bc0269c1c8d7b0873df15fdf601f72a1e8e2ea78df0c72504c9bc317b8f7" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/ecf859ade76d0d7ba46a0becb1455e15b0d4f047b517dbced1edaca049a77730" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/4a4970573678e92f231247fe72baa5975405e647cedbea89e11e2ef85b12aea2" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/57a81abfaaea018fb9d147f6b5e122f02c099b7b295ee1d20bfefa0ff4fd2e54" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/bfd16a078eef3d64f28c2ce945523f9067dad199fe254b69662ee4b270144362" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/5e9a48f78043c090ad351a46d04c3cc2397e7e79cd8557c206b2859f4076fbe3" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/af5b86fd118614ca07b7f4ac7444372c92380a206024ee072652cffe5e1dbcaf" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/aec789117196e32c22396de4910cce6a105a098de37797c5d1d5849ebd8aa238" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/1bf9a2d9268c56bd777c4d7a50e5822aa2800df297bbcdc32d150489296f1c63" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/d73c48751780fe0182d4f2c5057e9c894f6ccf06f008075ed6b09503684944f3" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/6cf411d0f73e890bb27a195cb5d3ed7d96fd8dc096b8fb116c838883bf87965e" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/f3a086145e5de802d450e132f9b39324251cb62f5aebe3e137d4d4036dfc2227" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/da3bc115f85063cf2d0145346d09e089dfb49a1105b696af9ef797452c7ebd33" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/8f692b340a8b6e9e2f96b5f3c7d0c7de7856586f5e4d6b9b86b60871adb3f9f5" has an unexpected source: "default" 
WARNING MountPoint property for "extra/docker/4224f2470d0a254c9af8275529ffc5d00b56671cdf13b3ac87f2bfef652420c9" has an unexpected source: "default" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92d039]

goroutine 1 [running]:
github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets(0xc0000acf00, 0xc0001268d0, 0xbc3ee0, 0x1015598, 0x9de4c0, 0x8e09f0, 0xa25220)
	github.com/ubuntu/zsys/internal/zfs/zfs.go:145 +0x199
github.com/ubuntu/zsys/internal/machines.(*Machines).refresh(0xc000cc25b0, 0xbc2de0, 0xc0000b2020)
	github.com/ubuntu/zsys/internal/machines/machines.go:152 +0xff
github.com/ubuntu/zsys/internal/machines.New(0xbc2de0, 0xc0000b2020, 0xc0000b0200, 0x78, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ubuntu/zsys/internal/machines/machines.go:129 +0x673
github.com/ubuntu/zsys/cmd/zsysd/daemon.syncBootPrepare(0x0, 0x0)
	github.com/ubuntu/zsys/cmd/zsysd/daemon/boot.go:18 +0x1d7
github.com/ubuntu/zsys/cmd/zsysd/daemon.glob..func3(0xfac340, 0x1015598, 0x0, 0x0)
	github.com/ubuntu/zsys/cmd/zsysd/daemon/zsysd.go:55 +0x22
github.com/ubuntu/zsys/vendor/github.com/spf13/cobra.(*Command).execute(0xfac340, 0x1015598, 0x0, 0x0, 0xfac340, 0x1015598)
	github.com/ubuntu/zsys/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/ubuntu/zsys/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xfac0c0, 0xb, 0x7ffeba141e54, 0x5)
	github.com/ubuntu/zsys/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/ubuntu/zsys/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	github.com/ubuntu/zsys/vendor/github.com/spf13/cobra/command.go:864
main.main()
	github.com/ubuntu/zsys/cmd/zsysd/main.go:34 +0xcd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x9350a3]

goroutine 11 [running]:
github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0x0)
	github.com/ubuntu/zsys/internal/zfs/zfs.go:134 +0x43
github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0xc000b7e200)
	github.com/ubuntu/zsys/internal/zfs/zfs.go:135 +0x75
github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0xc000b58900)
	github.com/ubuntu/zsys/internal/zfs/zfs.go:135 +0x75
github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0xc0000acf00)
	github.com/ubuntu/zsys/internal/zfs/zfs.go:135 +0x75
created by github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets
	github.com/ubuntu/zsys/internal/zfs/zfs.go:141 +0xff
```

Unfortunately, when that happens, the system becomes unbootable. The process appears to delete `/run/systemd/generator/boot.mount`, and then due to the segfault, the mount file isn't regenerated. So, upon reboot, `bpool` doesn't get mounted. Meanwhile, `/boot/efi` and `/boot/grub` get mounted due to processing of `/etc/fstab`, so those directories end up getting populated on `rpool`, which makes importing `bpool` thereafter fail until the contents of `/boot` is removed from `rpool`. Likewise, this causes the `rpool/ROOT/ubuntu_<id>/var/lib` dataset to fail to mount and then `/var/lib` is filled in with data, which blocks the mounting of that dataset from there on out. That's particularly problematic, because the newly populated `/var/lib` doesn't have `initramfs-tools`, which complicates fixing the boot problem.

I'm not sure what the problem is with that pool, but I also don't know why it's being processed at all, since I hadn't imported it. Assuming it does need to be processed, I think trying to make the `boot.mount` replacement atomic would be helpful. That way even if the processing of pools segfaults, you'd still be able to boot the system.

**Comment by didrocks** [comment]
Thanks for testing zsys and reporting this bug (and for the detailed bug report) :)
Indeed, we are running zsys early to avoid the issues are you pointed out with `var/lib` and being unable to import the pools and thus, segfaulted created the issues you mention.

However, we need to import all available pools at boot (and reexport the undeed ones) as you can revert and you may keep having activated datasets on different machines. Nothing ensures that the secondary machine doesn’t try to import current pool and so you will have conflict on boot for this secondary machine, trying to mount things on top of each other.

If we ignore the segfault of zsysd, it means in case you are reverting that we miss that and you end up with a mess of new datasets and old ones mounted on top of each other, which isn’t desirable (`rpool/ROOT/ubuntu_newdatasetforrevert` is created by the initiramfs, and the other pools, by zsysd on boot).

And finally, we can’t import all pools are read-only as we change properties and clones when you are reverting (and we don’t know if you are reverting before zsys is started).
I would be interested to understand why zsysd is segfaulting with this pool in particular. Can you try booting on a livecd environment to install latest zsys from focal (0.4.2) and if this is still the case, that I send you some special binary so that we can debug this together? That would be tremendously useful.

Stay safe.

**Comment by nirvdrum** [comment]
@didrocks Thanks for looking.

This was happening with zsys from focal. The way I got into this situation is I had a root ZFS install with Ubuntu 19.10 (I think I started with 18.04) from the ZoL wiki. Somehow, that pool got damaged and couldn't import cleanly, but could import in read-only mode. There's an acknowledged bug in the OpenZFS tracker to address this, as it leads to a kernel panic.

I opted to start from scratch using Ubuntu 20.04 and let it manage the zpool setup. This, unfortunately, was a headache from the start. What I was hoping to do was keep the old pool around, since I could import it read-only, and copy files from a snapshot on it, as needed. This would be a lot faster than replicating back from my NAS. But, as soon as this old pool (single drive vdev) became available, the whole system refused to boot, dropping into a grub command prompt. I worked out this was a problem with having two pools named `rpool` and the old one being detected first.

I must have reinstalled the system 5 times before I realized what was going on. I'm working a bit from memory now, but the grub script for ZFS doesn't handle two pools having the same name because it tries to import all pools at once. I think this process should import by pool ID instead of by name to avoid that particular conflict, but the pools also can't conflict on mountpoints. In that case, it should probably try to mount one at a time and re-export in between. These are all perfectly valid use cases with ZFS. The administrator doesn't have to import every pool and can provide a new mountpoint when doing so.

While I appreciate the idea, if all pools are going to be scanned at boot time, it needs to be resilient. I expect when I use grub, it will continue using the devices configured when I last ran `update-grub`. I would not expect it to try booting from a completely new device just because it became available, ZFS or otherwise. I think this is another reason using the pool ID, rather than name, for operations. At least then you get consistent results.

In any event, since I can only rename the old, bad pool when importing and because the grub process was handling the import process, I couldn't just rename the old pool. Moreover, the drive is not hot pluggable, so I couldn't boot the system then re-add it (although I could boot with both pools available with the live CD, since I control the import process there). So, my next step was to clone the bad pool to a new pool (this still would be faster than streaming back from my NAS). The result of this process was the pool named `extra`. With this device, I could now attach it and boot, because the grub scanner only looked for things named "rpool" and/or I was able to change the mountpoints on the newly cloned pool to use something other than `/`.

So, now the system boots. I can run Ubuntu 20.04 fine. It looks to me like I fixed all the problems I had with the installation and boot process. I can even mount my newly cloned pool, `extra`, and everything works. That is, until I reboot the system. Then I encounter the problem I filed here where my system is back to not booting. Adding to the frustration is I never ran into any of these issues when I created the root device myself using the ZoL wiki.

Fixing the segfault would be great. I'm happy to assist in that -- I haven't wiped the problematic device to provide that help. But, I also don't know how to do without breaking my primary system's boot capabilities. If the new build segfaults again, I have to drop into a live CD, chroot the system, fix the various directories that got created, and run `zfs-mount-generator`. I've definitely gotten faster at this process, given all the practice I had running it, but it's a time-consuming process and I can only do it off-hours, since I need this machine to be running. That's why I contend this project ought to be more defensive about not leaving the system unbootable when a software error arises, which is an inevitable certainty. Given a choice between being able to boot my system at all or being able to revert to an older snapshot from grub, I'm going to want a bootable system. At least I can manually rollback snapshots then.

I ought to be able to throw some time at the problem this weekend, if you have a build available that you'd like me to try. In parallel, as a suggested failure case, please try add inga new pool to your system named `rpool` that you induce a failure on (with one dataset with a mountpoint of `/`), such that it mounts read-only, but not read-write. I think you'll see the general assertion that any pool that can be imported read-only can also be imported read-write will create problems. Another assumption that should present itself as problematic is that there's only one pool named `rpool` or one dataset with a mountpoint of `/`. That may be a bit harder to demonstrate though, because it depends on the pool list order, which I don't think the user has any control over. Maybe doing it in a VM would help?

**Comment by nirvdrum** [comment]
FYI, I had [filed an issue](https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1867007) with the grub team about importing the pool as ID and it looks like it's being addressed. I only mentioned it in my previous comment so you had the full context of what I was doing and what issues I encountered. I'm happy we're able to systematically tackle them.

**Comment by didrocks** [comment]
@nirvdrum No worry at all! Thanks for filing the grub issue abourt duplicate pool name. We opened one on launchpad as well as there are similar issues with the menu generation! Yeah, we have bugs, and this is why we didn’t get it out of experimental (balancing that with the new features which entered this cycle). I agree the zfs generator (which has some bugs upstream as well) is a tricky one because you couln't reboot your machine, and indeed, debugging them is complex (and you can see the whole class of issues which have some consequences from other issues and the debuggability of it…)

Sorry that you have to go over all this pain, but your detailed feedback is really valuable so that we can see it "in the wild", and the development releases (or experimental state) really helps to get it rock solid and resilient once it will be out of experimental landmarks.
Note that contrary to manually handling it, zsys starts (and will add in the coming cycles even more) features on top of zfs that helps managing and handling states and backup easy (for the human being, we hope :))

FYI, on the dupicated pool name, our approach for focal would be to append an id for now until we have grub aligned and can tackle the other fixes. As you noted, the most complex one is the grub menu generation via `update-grub` as we need to import all pools at the same time to know exactly what to list: boot pools can be separated, and it means that we will have to try every possible combination to find the right boot pool (which might not even exist) which the rpool. If multiple pools have the same name, we are kind of stuck there as it means ignoring completely some machines. So, indeed, this is complex and we are opened to any idea (as you see, just taking into account the ID, if grub supports that), doesn’t really help to detect the pools rpool/bpool associations.
Then, on initramfs, we only import the pools you have in your zfs list cache AND in the zpool.cache.

There is no assumption to only have one dataset which mountpoint is `/` in zsys, contrary to zfs (if both have canmount=on) and this is what zsys prevent explicitely to happen on your live system in the generator (before running upstream one which doesn’t have this protection)! But indeed, zsys creates multiples datasets with `/` as a mountpoint (which are state saving: clones which were, once, active datasets to which you can revert to). So this shouldn’t be an issue.

On the segfault, I think we can come to this:
1. if you don’t revert (which will be hard to detect, but I think we can) -> don’t even try running this boot prepare command. It will allow to at least being able to boot. However, it means as well that zsys will always crash and you won’t have any features (and this is also an advantage for us to debug, see below). I think we can detect the revert (which isn’t just about "booting on a snapshot" because a state can be a zfs clone) thanks to the zfs list cache + looking at current cmdline. A little sed would be involved but it shouldn’t be that bad.
2. if you do revert and there is this crash -> stop the mounts (ideally, even prevents booting to go on, I need to check if we can do that from the generator). It means that from now on, you can only boot in 1.
That’s for the resiliency part. I will open a bug (on our zfs generator patch) for this and fix it next week.

Now, as I would really want to zsys to run even in your use case with the broken pool, we can iterate and debug.
The idea is to get latest zsys 0.4.2 (from today), and try:
- import the broken pool
- ensure no zsysd is running (you can `sudo zsysctl service stop`)
- run `sudo zsysd -vv boot-prepare` (this is a hidden command) which will do nothing on your booted system, but will try to load the zfs state and the segfault should be shown.
- don’t forget to export the broken pool before next boot to avoid having to go on the livecd hell to restore things as you describe :)
This may not enough to debug it fully and we can iterate over next week if you don’t mind. The good part is that it should be quick to run and you don’t have to screw your system up for doing this test (hopefully :))

Thanks for the feedback and thanks in advance for helping tackling that issue!

**Comment by didrocks** [comment]
Hey!

So, we fixed the generator to be more reliable:
- only do extra processing if you don’t revert (run same root dataset as previous boot for a given system won’t start zsys or do any import) -> this will help to ensure you can always boot if you were able to boot on last time.
- only import the pools from zpool.cache for a given system. This ensures we don’t import conflicting rpool as this stage for instance and import what was seen as mandatory/desired in the last boot.
The side-effect is that those both changes allows to boot more quickly, especially when you don’t revert.
- if any import or zsys call fails when doing a revert -> drop to emergency target, log in dmesg exact error. This helps preventing systemd mounting datasets out of order and creating directories in `/boot` on the `/` dataset for instance which will then prevent any further mount. There is no easy way in systemd to have a generator stopping the boot, hence this solution which can’t easily display the error outside of the journal. At least, the user can reboot on the last current dataset (main grub entry) to fix the error.

Note that this help on multiple rpool or bpool, but that won’t really fix it: as you told, there is something to do grub-wise (and we should have a strategy for our grub menu generator as well), but also, there is an upstream ZFS issue with the generator: it creates `.mount` units with the pool name, which then, expect systemd to be able to import the pool by name, which thus fail. I added a systemd task to the bug on launchpad.

Some consequences is that you need to have an installation with [ubiquity 20.04.8](https://launchpad.net/ubuntu/+source/ubiquity/20.04.8) and [zfs-linux 0.8.3-1ubuntu10](https://launchpad.net/ubuntu/+source/zfs-linux/0.8.3-1ubuntu10). Ubuntu focal beta (which should be released this Thursday) should have them.

This should really help to address most of the points you mentioned above. Let me know if I missed anything.

I’m still interested in debugging the zsysd crash though, mind giving the above a try so that we can iterate on this? Thanks in advance!

**Comment by nirvdrum** [comment]
@didrocks I'm glad to hear the generator will be more reliable. I just ran the steps you outlined in your previous comment and I'm still seeing a segfault. The log is rather long so I [put it in a gist](https://gist.github.com/nirvdrum/67b9e496b215276538cbcf7bce6d3a4b). If you'd rather I put it here so there's no risk of the link going stale, I can do that as well.

I've also verified that `zfs-mount-generator` won't delete the `boot.mount` file. I did try moving that file to see if the generator would re-create it and it did not. But, it also looks like it didn't really run anything, which sounds like is by design now. I'm content with the boot.cache file not being deleted.

Unfortunately, I somehow still got my system into a strange boot state. grub launches fine, but the default kernel entry won't boot. Instead, I get this:

```
error: file `/ROOT/ubuntu_bp7ow2@/boot/vmlinuz-5.4.0-21-generic' not found.
error: you need to load the kernel first.

Press any key to continue...
```

Loading in recovery mode gives a similar message. However, I can pick an older entry in the history menu and boot up.

When I got booted back up using a reverted version of the system (i.e., I didn't revert user files), I ran `update-grub` and got an error I hadn't been seeing previously (found images removed for brevity):

```
/usr/sbin/grub-probe: error: unknown filesystem.
device-mapper: reload ioctl on osprober-linux-nvme0n1p4  failed: Device or resource busy
Command failed.
```

nvme0n1p4 is the only drive in the `rpool` pool.

Each time I boot like that (i.e., with a system revert), I end up with new datasets for the new system ID (I'm not really sure what it's called, but the random identifier after `rpool/ROOT/ubuntu_`). None of these new datasets show up under `sudo zsysctl machine list`, so I don't really know how I'm supposed to manage them. Any thoughts on what's going on now or how to fix it?

**Comment by didrocks** [comment]
Thanks a lot for testing this!

1. Let’s start on the segfault…
The good news is that it doesn’t segfault when doing the initial scan of the datasets, but rather, the first time we build the machine list from it. I’m puzzled about why this happens in your case and not in the general one (nor in the 560 tests we run :p). I built a special binary with additional print specifically where it’s failing, mind giving it a look?
The binary is at `http://people.canonical.com/~didrocks/tmp/zsysd`, you can copy it anywhere, just execute it as before (no need for `-vv` anymore). Mind also sharing `zfs list -t all` output?

2. on grub menu entry: interesting, this is like it found an invalid entry and grub can’t boot it? (You don’t have multiple rpool or bpool anymore, correct?). I suggest this:
- run `update-grub`
- look at the first zfs entry (from `10_linux_zfs`) in `/boot/grub/grub.cfg`. Note down the datasets path, kernel and initrd.
-> match them:
  * `zfs mount` should show the correct / dataset next to `ZFS=root=`
  * the kernel and initrd path should be on the right /boot dataset (it will have an additional "@/" in the name) and the kernel/initrd is at the root of this dataset (as it’s mounted directly on `/boot`)
  * the drive on where it will try to find this kernel should match as well, but translated in grub form. For this, run:  `grub-probe --target=device /boot/initrd.img`. In my case, the output is  `/dev/sda2`, which in grub/gpt world is `set root='hd0,gpt2'` (second partition of hd0 device).

Check thus that this entry is correct. The fact that your current entry starts with /**R**OOT/ubuntu_bp7ow2@ and not /**B**OOT/ubuntu_bp7ow2@ makes me think that you still have a fallover of the previous generator outuput, which couldn’t mount bpool (due to multiple rpool and bpool attached), and which created thus a `/boot/*` content on your root dataset. This folder is supposed to be empty.
I think the grub-probe error is a fallover of that (as grub won’t handle that gracefully).

I think you have 2 options for 2: either trying to fix to match the correct layout by removing kernels and ensuring that before running update-grub, bpool is mounted on /boot, with kernels and initrd 
and grub partition on top of it (and that there is no other rpool/bpool attached to your system). Then, you will be able to boot the main entry. The other (simplest option) would be to reinstall to start from scratch (with the beta 2 image which is due tomorrow). It seems you already have done the first option with a livecd, can you check this matches what I described above? If not, I’m happy to help fixing your layout as you seem to be the only one to get into this (all this started due to zsys failing on early boot, and fortunately, thanks to you, this is now prevented in the new generator patch).

Just to be clear: multiple rpool/bpool is still not supported (due to systemd and grub). We have that on our list (probably post-release though).

3. The new dataset on revert is expected (we creates a clone) and zsys will garbage collect older ones after a while (multiple days). The history isn’t linear and you will be able to revert the revert this way (which you can’t with pure zfs as rollback destroys all intermediate snapshots while we are keeping them and garbage collect with zsys). The issue of now showing up in machine list is due to the fact that they are not fully committed (as zsysd crash on boot). Let’s fix that first :)

Thanks for again in here and for testing the alpha, this is what helps us not having this kind of issues only reported on the release day :)

**Comment by nirvdrum** [comment]
Correct. Single bpool and single rpool in this latest case. I've never had more than one bpool. The old ZoL wiki page didn't provide any info on how to install `/boot` onto ZFS, so my old system used a non-ZFS partition for `boot`. I'll try running through your other steps.

**Comment by didrocks** [comment]
I think the attached PR has a fix for your use-case (the crash was created by the swap volume). We are fixing the warnings at the same time.

Thanks a lot for your help there!

**Comment by nirvdrum** [comment]
@didrocks No problem. I'm sorry I haven't been able to test builds as quickly as I'd like. It's still a time-consuming affair that knocks my system offline. But, I should have some time over the next couple days if you have a build you'd like me to try.

**Comment by didrocks** [comment]
Sure! No worry but if you can confirm this is the same issue before we release, that would be awesome!

You can find the new binary with this fix and many others at the same address: `http://people.canonical.com/~didrocks/tmp/zsysd`.

Note that you shouldn’t have any warnings displayed anymore as well, feel free to paste the output if any are left.

**Comment by didrocks** [comment]
I’m closing this for now. The new version of zsys is available in focal (0.4.3) which has this fix. Please reopen it if you still have the crash with an updated backtrace.

The only "remaining" issue is if you have multiple rpool/bpool that is tracked on your grub bug report. All other points should be addressed now.

**Comment by nirvdrum** [comment]
Thanks for all the hard work on this one. I've just verified my issue here was fixed with 0.4.3. The `boot-prepare` command runs without errors now and my system is bootable upon reboot. Thanks again. I'm glad you were able to get this for the 20.04 release.

**Comment by didrocks** [comment]
Excellent! Thanks for confirming :)
